### ISSUE TITLE
Error when minifyEnabled true ini gradle script

### ISSUE THREAD

**Issue by ptsagkis** [orbisgis/cts#102]
Hi there,

I am developing an android app that executes some projection transformations. 
Recently I face the following problem. 
When I set on gradle script `minifyEnabled true` my apk may be build without any errors, but when I call 

`GeodeticCRS targetGCRS = (GeodeticCRS) cRSFactory.getCRS(epsgCode);` I get the following error 

`Unable to access CRS file: epsg` . And this is happening only when `minifyEnabled true`.  So it seems there is a confusion with class names of CTS when obfuscation takes place. (check [1](https://stackoverflow.com/questions/39098768/after-setting-the-minifyenabled-as-true-im-getting-the-following-error) and [2](https://stackoverflow.com/questions/36249005/minifyenabled-true-leads-to-crash-on-app-start) stackoverflow links) 
I ended up excluding org.cts from the process of obfuscation .
To do so you just need to add the following line in proguard file of the app. 
`-keep class org.cts.** { *; }`
In my case I added the line  above in  `proguard-rules.pro` file which is configured to be used in my gradle script. 

And inside my gradle script I do force my app to use this proguard file. 
![default](https://user-images.githubusercontent.com/15774617/52472969-58221800-2b9d-11e9-976f-7b7cd1d1144c.png)

And here is the location of my proguard file
![default](https://user-images.githubusercontent.com/15774617/52473101-a6371b80-2b9d-11e9-9873-da552e90293a.png)

An finally the contents of the file
![default](https://user-images.githubusercontent.com/15774617/52473150-c666da80-2b9d-11e9-8387-84ec7f1fb00f.png)

I dont expect any action, I just share my workaround for people facing the same problem. 

1. https://stackoverflow.com/questions/39098768/after-setting-the-minifyenabled-as-true-im-getting-the-following-error
2. https://stackoverflow.com/questions/36249005/minifyenabled-true-leads-to-crash-on-app-start

**Comment by SPalominos** [comment]
Thank you very much for the troubleshoot!
We have added it to the wiki to keep track of it.
