### ISSUE TITLE
Could not get CRS definition for a few EPSG codes

### ISSUE THREAD

**Issue by AndreeaCh** [orbisgis/cts#103]
Could not get CRS definition for the following codes
- EPSG:4299
- EPSG:4300
- EPSG:4002
- EPSG:29900
- EPSG:29903
- EPSG:29902

The code below results in a CRSException:
CRSFactory cRSFactory = new CRSFactory();
RegistryManager registryManager = cRSFactory.getRegistryManager();
registryManager.addRegistry(new EPSGRegistry());
...
epsgRegistry.getCoordinateReferenceSystem(new Identifier(EPSG, "4299", ""));
OR
CoordinateReferenceSystem crs = crsFactory.getCRS(srid);

**Comment by ebocher** [comment]
Under the pipe for  EPSG:4300;EPSG:4002;;EPSG:29903

see https://github.com/orbisgis/cts/pull/110

Some fixes needed for https://github.com/orbisgis/cts/issues/109

You are welcome to submit a patch
