### ISSUE TITLE
Add EPSG:7405 to registry

### ISSUE THREAD

**Issue by AndreeaCh** [orbisgis/cts#104]
An update of the registry would be nice.

**Comment by ebocher** [comment]
Sorry but we do not support correctly vertical transformation.
@mukoki  any comment or suggestion

**Comment by robo-w** [comment]
EPSG 7405 is in fact EPSG:27700 with an additional altitude. If the -vunits parameter is omitted, it works out fine (See https://github.com/robo-w/cts/commit/3a5e0c33ce0bf5f1de37ff2280951069e8dac80a)

I think to keep the epsg definition clean, EPSG 7405 should not be added, although the transformation of the relevant coordinates would be supported.

**Comment by mukoki** [comment]
To explain it simply, CTS can compute 3D transformations but cannot read compound CRS definition.
Indeed, I don't know it there is a standard way to define compound CRS in WKT or prj files. 
Currently, CTS has only been tested with compound CRS defined by IGN (France) with geoids defined in .mnt files wich may not be a standard.
