### ISSUE TITLE
EPSG:4299 bad recursive call

### ISSUE THREAD

**Issue by ebocher** [orbisgis/cts#109]
The EPSG:4299 introduces a bad recursive call

See the test : 

49;EPSG:4326;-7.899170;52.831312;EPSG:4299;-7.89842402505289;52.8310168494995;0.0000001

in BatchCoordinateTransformTest

**Comment by ebocher** [comment]
Same for : 

#Bug ->52;EPSG:4326;-7.899170;52.831312;EPSG:29900;206845.456303112;175560.736757651;0.001

#Bug ->54;EPSG:4326;-7.899170;52.831312;EPSG:29902;206845.456303112;175560.736757651;0.01

**Comment by mukoki** [comment]
Should fix the bug.
Note that I manually added the 3 tests number 49, 52 and 54 included in the report as I did not see them in the master (you may have more tests in your local repo).

**Comment by ebocher** [comment]
Thanks the tests were here https://github.com/orbisgis/cts/pull/110
I will merge.

**Comment by ebocher** [comment]
Fixed thanks a lot to @mukoki
