### ISSUE TITLE
CRS create from Proj4 string format

### ISSUE THREAD

**Issue by phammanhdam** [orbisgis/cts#117]
Hello, I have a issues with proj4 format. How to create object CoordinateReferenceSystem from proj4 format as sample bellow. I just can create from WKT format in your library. Thank you so much.

+proj=tmerc +lat_0=0 +lon_0=106 +k=1 +x_0=500000 +y_0=0 +ellps=krass +towgs84=-17.51,-108.32,-62.39,0,0,0,0 +units=m +no_defs

**Comment by ebocher** [comment]
Done in current master
