### ISSUE TITLE
GeographicExtent getEasternBound returns westernBound incorrectly

### ISSUE THREAD

**Issue by hramlee** [orbisgis/cts#136]
Hi, 

I was trying to use GeographicExtent to write a version of isInside, but ignoring the modulo, when I noticed that the getter for EasternBound returns westernBound instead in org.cts.cs.GeographicExtent

    public double getEasternBound() {
        return westernBound;
    }

**Comment by ebocher** [comment]
@mukoki  if you have time

**Comment by mukoki** [comment]
Sorry for the late answer and thanks for the reminder. Should be fixed by #137
