### ISSUE TITLE
No projection for elements in the epsg register that have ellipsoid: +ellps=aust_SA

### ISSUE THREAD

**Issue by pshepherd27** [orbisgis/cts#149]
CRSHelper:getEllipsoid parses the ellipsoid name using:
            ellps = Ellipsoid.ellipsoidFromName.get(ellipsoidName.replaceAll("[^a-zA-Z0-9_]", "").toLowerCase());

Consequently it does not remove the underscore.

For example, it computse the ellipsoide for EPSG:20256 as "aust_sa", which does not match the name used internally by the  org.cts classes.

The solution is to use:
    ellps = Ellipsoid.ellipsoidFromName.get(ellipsoidName.replaceAll("[^a-zA-Z0-9]", "").toLowerCase());

**Comment by ebocher** [comment]
Thanks we will check

**Comment by ebocher** [comment]
Thanks !
