### ISSUE TITLE
System.out.println() statements

### ISSUE THREAD

**Issue by mainkai** [orbisgis/cts#66]
Hey there,
thanks for this great project.
But could you please remove/comment out the System.out.println() statements in your code?
More specifically, I am talking about LambertAzimuthalEqualArea class, inverse() method (line 178).

I assume it was necessary for debugging, but for people using the suite, it can be annyoing.

Regards,
Kai

**Comment by nicolas-f** [comment]
Yes, thank you for this notification. https://github.com/orbisgis/cts/blob/master/src/main/java/org/cts/crs/CompoundCRS.java#L182 should throw an error instead of println also.

**Comment by mainkai** [comment]
Thanks for adding it to the milestone. When can we expect this to be fixed? I think it is really slowing down my application...

**Comment by ebocher** [comment]
Fixed

**Comment by mainkai** [comment]
Thanks for the quick response, but this one seems to remain:
https://github.com/orbisgis/cts/blob/master/src/main/java/org/cts/op/projection/LambertAzimuthalEqualArea.java#L171

**Comment by ebocher** [comment]
done

**Comment by mainkai** [comment]
Thanks a lot!
Will there be a new .jar file that reflects these changes?

**Comment by nicolas-f** [comment]
A remaining one
https://github.com/orbisgis/cts/blob/master/src/main/java/org/cts/CRSHelper.java#L534
