### ISSUE TITLE
Authority name and key should be case insensitive

### ISSUE THREAD

**Issue by mukoki** [orbisgis/cts#78]
In CRSHelper#createCoordinateReferenceSystem(), we use the following test :
`if (identifier.getCode().equals("EPSG:3857")) {}`
and registry name like that 
`EPSGRegistry.getRegistryName() {return "epsg";}`

I suggest 
1 - to always use uppercase registry names in the code (e.g. in EPSGRegistry, ESRIRegistry, IGNFRegistry)
2 - to make all comparison of authorityName and authorityId case insensitive, and in particular in
    CRSHelper#createCoordinateReferenceSystem
    Identifier#equals, Identifier#hashCode
    IdentifiableComponent#equals, IdentifiableComponent#hashcode
    etc.

**Comment by ebocher** [comment]
Thanks a lot @mukoki 
I have a preference for the second option. It will be more comfortable for users or developers.

**Comment by ebocher** [comment]
I will start to merge the @mukoki PR into CTS.
