### ISSUE TITLE
Parameter precision in WKT writer

### ISSUE THREAD

**Issue by mukoki** [orbisgis/cts#87]
Currently, WKT Writer retains a maximum of 11 decimals when it writes parameter values. Although 11 decimal is generally a good precision for parameters either in meters or in degrees, I think that it is not good to change the precision at this stage.
I tried to write a method which solve some rounding problems when values like 500000.000003 or 14.9999999998 are found in parameters, without loosing precision, but I think the simplest way would be to write doubles as is, without rounding and without special processing. What do you think and why did you choose to round to 1E-11 ?

**Comment by ebocher** [comment]
I'm agree to keep the precision as is.
